
# EXAMPLE 0: HOW DOES END=" " WORK IN PYTHON
#HOW DOES THE END PARAMETER IN THE PRINT FUNCTION WORKS
"""
PREVIOUSLY, THE PRINT FUNCTION ADDS NEWLINE AFTER IT PRINTS ITS STATEMENTS.
SO IF WE WANT TO CONCATINATE THE STATEMENTS OF TWO PRINTS WE USE END PARAMETER TO IGNORE THE NEW LINE
THE END=" " WITH SPACE OR NO SPACE INSIDE THE QUATATION WILL TELL THE COMPILER TO USE SPACE INSTEAD OF ADDING NEW LINE AFTER THE
PRINT FUNCTION
"""
#EXAMPLE 0.0: DISPLAY WHILE CONCATINATING TWO STRINGS FROM PRINT FUNCTION INTO ONE LINE
print("PYTHON IS A ", end='')
print("GOOD LANGUAGE")

#EXAMPLE 1: PRINT PYRAMID PATTERN OF ASTRIK USING NESTED FOR LOOP IN PYTHON
print("\n")
for i in range(6):
    for x in range(i):
        print("*", end=' ')
    print(" ")

#EXAMPLE :2 PRINT PYRAMID PATTERN OF NUMBERS USING NESTED FOR LOOP IN PYTHON
"""print(" ")
rows =6
for i in range(1,rows+1):
    for x in range(1,i+1):
        print("THE V OF I : ",i," THE V IF X : ",x)
    print(" ")
"""
#EXAMPLE :3 PRINT PYRAMID PATTERN OF NUMBERS USING NESTED FOR LOOP IN PYTHON
print("")
rows = 5
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end="")
    print('')

#TODO MORE PATTERNS IN FUTURE AND TRY TO UNDERSTAND THE WAY NESTED LOOP WORKS